---
# This should no longer be necessary now that homebrew autotaps based on FQ name
# TODO: remove me once I verify a full install run worked properly without it.
#
# - name: set up sources
#   hosts: all
#   tags: casks
#   tasks:
#   - name: get homebrew taps setup
#     homebrew_tap: tap={{ item }} state=present
#     always_run: yes
#     with_items:
#       - homebrew/binary

- name: essential tools for shell environment
  hosts: all
  tags: essential
  tasks:
  - name: install essential shell brews
    homebrew: name={{ item }} state=present
    with_items:
      - git
      - coreutils
      - hub
      - scmpuff
      - ssh-copy-id
      - imagemagick

# More complex development environments I manage with their own playbooks,
# import the ones I want installed here.
- import_playbook: playbooks/development/elixir.yml
- import_playbook: playbooks/development/go.yml
- import_playbook: playbooks/development/node.yml
- import_playbook: playbooks/development/ruby.yml
- import_playbook: playbooks/development/rust.yml
- import_playbook: playbooks/development/ios.yml
- import_playbook: playbooks/development/vscode.yml

# More and more these days, I'm actually avoring using Docker to manage local
# dev environments, making the playbooks like the above unnecessary (but it's
# still nice to have the ability to do local dev, hence I still have them for
# more frequently used environments.)
- import_playbook: playbooks/development/docker.yml

- name: Applications and tools
  hosts: all
  tasks:
  - name: install brewcask applications
    tags: casks
    homebrew_cask: state=present name={{ item }}
    with_items:
      # webdevs need all the webs (except opera lol)
      - google-chrome
      - firefox
      # VMs and containers
      - vmware-fusion
      # other dev tools
      - dash
      - github
      - gitup
      - imageoptim
      - licecap
      # non-dev stuff for general productivity
      # - daisydisk (I bought this in MAS whoops)
      # non-dev stuff for general unproductivity (games, media, torrents)
      - brogue
      - dungeon-crawl-stone-soup-tiles
      - transmission
      - vlc
      - iina

  - name: install homebrew tools
    tags: brews
    homebrew: state=present name={{ item }}
    with_items:
      # General dev tools useful on the command line.
      - ack
      - ripgrep
      - jq
      - gist
      # Some small custom tools I use for command line productivity,
      # but not in enough demand to actually submit to homebrew central.
      - mroth/formulas/readtime     # see github.com/mroth/readtime
      - mroth/formulas/timeduration # see github.com/mroth/timeduration
      # let us avoid global gems as distribution tool
      - brew-gem
      # Linters, etc that aren't part of a general dev environment.
      - shellcheck
      # Tools to aide Heroku deployments.  I do this less often these days,
      # but still handy to have around.
      - heroku-toolbelt
      - forego
      # networking tools
      - curl
      - wget
      - speedtest_cli
      # security tools
      - gnupg
      - nmap
      - pwgen
